### ISSUE TITLE
Missing schema error in python 3.7

### ISSUE THREAD

**Issue by sandorkruk** [zooniverse/panoptes-cli#104]
I get the following **MissingSchema** error when running panoptes configure, or panoptes project. Installing the client worked well though. 

```
(base) smac105041:~ skruk$ python --version
Python 3.7.2
(base) smac105041:~ skruk$ pip --version
pip 18.1 from /Users/skruk/anaconda3/lib/python3.7/site-packages/pip (python 3.7)
(base) smac105041:~ skruk$ panoptes configure 
Broken libmagic installation detected. The python-magic module is installed but can't be imported. Please check that both python-magic and the libmagic shared library are installed correctly. Uploading media other than images may not work.
Traceback (most recent call last):
  File "/Users/skruk/anaconda3/bin/panoptes", line 11, in <module>
    sys.exit(cli())
  File "/Users/skruk/anaconda3/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/skruk/anaconda3/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/skruk/anaconda3/lib/python3.7/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/Users/skruk/anaconda3/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/skruk/anaconda3/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/skruk/anaconda3/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/skruk/anaconda3/lib/python3.7/site-packages/panoptes_cli/scripts/panoptes.py", line 47, in cli
    admin=admin,
  File "/Users/skruk/anaconda3/lib/python3.7/site-packages/panoptes_client/panoptes.py", line 108, in connect
    cls._local.panoptes_client = cls(*args, **kwargs)
  File "/Users/skruk/anaconda3/lib/python3.7/site-packages/panoptes_client/panoptes.py", line 140, in __init__
    self.login()
  File "/Users/skruk/anaconda3/lib/python3.7/site-packages/panoptes_client/panoptes.py", line 484, in login
    'authenticity_token': self.get_csrf_token(),
  File "/Users/skruk/anaconda3/lib/python3.7/site-packages/panoptes_client/panoptes.py", line 519, in get_csrf_token
    return self.session.get(url, headers=headers).headers['x-csrf-token']
  File "/Users/skruk/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 537, in get
    return self.request('GET', url, **kwargs)
  File "/Users/skruk/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 510, in request
    prep = self.prepare_request(req)
  File "/Users/skruk/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 453, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/skruk/anaconda3/lib/python3.7/site-packages/requests/models.py", line 313, in prepare                                  /users/sign_in?
(base) smac105041:~ skruk$ arams)
  File "/Users/skruk/anaconda3/lib/python3.7/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '\x1b[A\x1b[A\x1b[A\x1b[A/users/sign_in': No schema supplied. Perhaps you meant http://

```

**Comment by adammcmaster** [comment]
Looks like the endpoint specified in your config file is invalid (the lack of validation there is a known issue #96). If you run `panoptes configure` then just enter `https://www.zooniverse.org` as the endpoint it should work.
