### ISSUE TITLE
panoptes configure breaks with "Invalid email or password error"

### ISSUE THREAD

**Issue by psilonpneuma** [zooniverse/panoptes-cli#122]
Hi!
I need to set up a project on zooniverse using audio files. For this, I think, I need to work through the zooniverse API. I have installed panoptescli following the steps in (https://github.com/zooniverse/panoptes-cli).
I am running Python 3.6.8 (Anaconda distribution) on OSX. I have tried installing and uninstalling the package several times, and running it from different virtual environments, but I cannot seem to get past the following error, when I run "panoptes configure":

```
$ panoptes configure
Broken libmagic installation detected. The python-magic module is installed but can't be imported. Please check that both python-magic and the libmagic shared library are installed correctly. Uploading media other than images may not work.
Traceback (most recent call last):
  File "/Users/cs/anaconda3/bin/panoptes", line 10, in <module>
    sys.exit(cli())
  File "/Users/cs/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/cs/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/cs/anaconda3/lib/python3.6/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/Users/cs/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/cs/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/cs/anaconda3/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/cs/anaconda3/lib/python3.6/site-packages/panoptes_cli/scripts/panoptes.py", line 47, in cli
    admin=admin,
  File "/Users/cs/anaconda3/lib/python3.6/site-packages/panoptes_client/panoptes.py", line 108, in connect
    cls._local.panoptes_client = cls(*args, **kwargs)
  File "/Users/cs/anaconda3/lib/python3.6/site-packages/panoptes_client/panoptes.py", line 140, in __init__
    self.login()
  File "/Users/cs/anaconda3/lib/python3.6/site-packages/panoptes_client/panoptes.py", line 501, in login
    response.json().get('error', 'Login failed')
panoptes_client.panoptes.PanoptesAPIException: Invalid email or password.

```

How can I configure the email and password properly? Or am I missing some steps?

Thank you so much in advance for the help.

**Comment by adammcmaster** [comment]
Sorry for the trouble – this is a known issue in the current version where having an incorrect password in the config stops the configure command from working. If you run `rm ~/.panoptes/config.yml` you should then be able to configure it. (This has been fixed in the next version of the CLI, which is coming soon.)
