### ISSUE TITLE
CLI errors after upgrading to 1.1

### ISSUE THREAD

**Issue by camallen** [zooniverse/panoptes-cli#138]
running `panoptes project --help` after upgrading and results in the following stack trace. Something to do with the yaml config? `panoptes configure` errors too :(
```
$ panoptes project --help
No handlers could be found for logger "panoptes_client"
Traceback (most recent call last):
  File "/Users/camallen/Library/Python/2.7/bin/panoptes", line 11, in <module>
    load_entry_point('panoptescli==1.1', 'console_scripts', 'panoptes')()
  File "/Users/camallen/Library/Python/2.7/lib/python/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/camallen/Library/Python/2.7/lib/python/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/camallen/Library/Python/2.7/lib/python/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/Users/camallen/Library/Python/2.7/lib/python/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/camallen/Library/Python/2.7/lib/python/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/camallen/Library/Python/2.7/lib/python/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/camallen/Library/Python/2.7/lib/python/site-packages/panoptes_cli/scripts/panoptes.py", line 36, in cli
    ctx.config.update(yaml.full_load(conf_f))
AttributeError: 'module' object has no attribute 'full_load'
```

**Comment by adammcmaster** [comment]
Thanks! I guess one downside to developing in Docker is that it's always installing the newest version of dependencies.

**Comment by camallen** [comment]
OOI - will you release a patch version for the PIP cli package? It's borked right now :(

**Comment by adammcmaster** [comment]
Yup, that's out now.
