### ISSUE TITLE
Moving subjects between workflows (stats not reset)

### ISSUE THREAD

**Issue by denslowm** [zooniverse/panoptes-cli#176]
Here is the command I used to move the subjects from our old project to the new Org.:
`panoptes workflow add-subject-sets 14155 74865`

14155 was a test workflow. Once I ran the command it made a new subject set in my Org. (#82902). I assume the subject set is identical, but I didn't do any formal check on that. I then associated that "new" subject set with the correct workflow.

The stats are not correct once it goes active. Note that this particular example has been resolved since someone "reset the subject count" for me. However, I have a series of subjects sets that I still need to move and I am trying to determine the best way to do that and there is another command I should be using.

**Comment by camallen** [comment]
Your cli cmds are correct. We've got a PR fix in the API repo for this https://github.com/zooniverse/panoptes/pull/3458

Hopefully we get that merged and deployed this week for you, thanks for reporting.

**Comment by denslowm** [comment]
One other thing that I failed to notice previously is that subject "Notes" for these subjects are also showing up in the previous project (decommissioned now) if the subject was commented on there. This means that we have Notes going into two different places. I assume that this is not desired behavior either. 

Will the fix address that as well?

Also, I assume I am waiting on the actual merge in #3458 , is that correct?

**Comment by camallen** [comment]
https://github.com/zooniverse/panoptes-cli/issues/176#issuecomment-684863751 is not related to this code repository. Can you please open an issue on https://github.com/zooniverse/panoptes-front-end/issues

**Comment by denslowm** [comment]
Cam,

I ran the following this AM. 

'panoptes workflow add-subject-sets 14155 20896'

I get the following messages. Should I be concerned? A new subject set is made (# 87353) and it seems the have the correct number of subjects. I just wanted to check before I activate the workflow. 

No handlers could be found for logger "panoptes_client"
Traceback (most recent call last):
  File "/Users/michaeldenslow/panoptes/venv/bin/panoptes", line 10, in <module>
    sys.exit(cli())
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/panoptes_cli/commands/workflow.py", line 87, in add_subject_sets
    workflow.add_subject_sets(subject_set_ids)
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/panoptes_client/workflow.py", line 66, in add_subject_sets
    return self.links.subject_sets.add(subject_sets)
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/panoptes_client/utils.py", line 56, in do_batch
    func(_self, batch, *args, **kwargs)
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 1044, in add
    retry=True,
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 633, in http_post
    **kwargs
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 404, in post
    retry=retry,
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 281, in json_request
    json_response['errors']
panoptes_client.panoptes.PanoptesAPIException: Validation failed: Display name has already been taken

**Comment by camallen** [comment]
>  panoptes_client.panoptes.PanoptesAPIException: Validation failed: Display name has already been taken
Hmm - the error above indicates you have a subject set in your project with the default name. Please rename that subject set and try again.

**Comment by denslowm** [comment]
Is the default name 'Untitled subject set?'

**Comment by camallen** [comment]
yes i believe so

**Comment by camallen** [comment]
It appears you already have a subject set in your target workflow with the same name as the original set (id: 20896) - hence the failure message. Subject sets have to be uniquely named in each project.

The workflow has subject set NitFix5 (NYBG visit 2-4) with id 87353, you have tried to copy from set 20896

Try `$ panoptes subject-set info 20896` to get more information on the source subject set, it appears to be from a much earlier project (id: 1558')

**Comment by denslowm** [comment]
I was assuming that NitFix5 (NYBG visit 2-4) (id 87353) was the new version of 20896. I thought it was created by `panoptes workflow add-subject-sets 14155 20896` as I don't think it was there previously and I assumed it took the same name. 
My goal is to use the old subject set from the older project in my new project.

**Comment by camallen** [comment]
I really don't know. I've tested those commands on my projects and I have;
1. verified it works and copies the set across
2. reproduced the duplicate set name error you saw

I suggest getting a subject export and verifying the data you want in the new set is the same as the old set. Or maybe rename the `NitFix5 (NYBG visit 2-4) (id 87353)` subject set and run the original cmd again `panoptes workflow add-subject-sets 14155 20896`

**Comment by denslowm** [comment]
OK, I renamed and tried again. Same result, so I assume that the error is incorrect. 

I linked the moved subject set and activated the workflow. The stats seem to be progressing as expected, so I guess this issue should be closed.
