### ISSUE TITLE
failed subject uploads - how to avoid?

### ISSUE THREAD

**Issue by camallen** [zooniverse/panoptes-cli#193]
Reports of a direct failure of the upload subjects command  the errors are the following:
1. `ConnectionResetError: [Errno 104] Connection reset by peer`
2. `urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))`
3. `requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))`

These appear to be issues with both our CDN (Azure Front Door) and the Azure storage account (blob store). I'm actively debugging these issues with Azure support  (albeit slowly). 

**I'd like to know if the retry mechanism is in play on subject uploads (Post requests)?** 

Looking at https://github.com/zooniverse/panoptes-python-client/blob/7dc7318d79065216c8857a1d142f771b81d461b3/panoptes_client/panoptes.py#L627-L634 it appears that retry is disable for non-get requests. 

FWIW I assume retrying on POST is not a viable solution due to the type of failure mode i.e. did the response succeed at the server. And as such we can look to rely on the 'resume' mechanism of the upload cli code, https://github.com/zooniverse/panoptes-cli#resuming-a-failed-upload

Log of the upload failure thanks to @SonjaNilson 
```
$ panoptes subject-set upload-subjects -m image/jpeg -r 1 92488 manifest.csv
Uploading subjects  [#-----------------------------------]    2%  02:11:08Error: Upload failed.
Would you like to save the upload state to resume the upload later? [Y/n]: y
Enter filename to save to [panoptes-upload-92488.yaml]: panoptes-upload-92488.yaml

Traceback (most recent call last):
  File "/home/sonja/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/home/sonja/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/sonja/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/home/sonja/anaconda3/lib/python3.8/http/client.py", line 1332, in getresponse
    response.begin()
  File "/home/sonja/anaconda3/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/home/sonja/anaconda3/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/sonja/anaconda3/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/home/sonja/anaconda3/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/home/sonja/anaconda3/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sonja/anaconda3/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/sonja/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/home/sonja/anaconda3/lib/python3.8/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/sonja/anaconda3/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/home/sonja/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/home/sonja/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/sonja/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/home/sonja/anaconda3/lib/python3.8/http/client.py", line 1332, in getresponse
    response.begin()
  File "/home/sonja/anaconda3/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/home/sonja/anaconda3/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/sonja/anaconda3/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/home/sonja/anaconda3/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/home/sonja/anaconda3/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sonja/anaconda3/bin/panoptes", line 8, in <module>
    sys.exit(cli())
  File "/home/sonja/anaconda3/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/sonja/anaconda3/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/sonja/anaconda3/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sonja/anaconda3/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sonja/anaconda3/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sonja/anaconda3/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/sonja/anaconda3/lib/python3.8/site-packages/panoptes_cli/commands/subject_set.py", line 411, in upload_subjects
    move_created(MAX_PENDING_SUBJECTS)
  File "/home/sonja/anaconda3/lib/python3.8/site-packages/panoptes_cli/commands/subject_set.py", line 382, in move_created
    if subject.async_save_result:
  File "/home/sonja/anaconda3/lib/python3.8/site-packages/panoptes_client/subject.py", line 205, in async_save_result
    self._async_future.result()
  File "/home/sonja/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/home/sonja/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/home/sonja/anaconda3/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/sonja/anaconda3/lib/python3.8/site-packages/panoptes_client/subject.py", line 139, in save
    response = retry(
  File "/home/sonja/.local/lib/python3.8/site-packages/redo/__init__.py", line 185, in retry
    return action(*args, **kwargs)
  File "/home/sonja/anaconda3/lib/python3.8/site-packages/panoptes_client/panoptes.py", line 810, in save
    response, response_etag = save_method(
  File "/home/sonja/anaconda3/lib/python3.8/site-packages/panoptes_client/panoptes.py", line 396, in post
    return self.json_request(
  File "/home/sonja/anaconda3/lib/python3.8/site-packages/panoptes_client/panoptes.py", line 259, in json_request
    response = self.http_request(
  File "/home/sonja/anaconda3/lib/python3.8/site-packages/panoptes_client/panoptes.py", line 231, in http_request
    response = self.session.request(
  File "/home/sonja/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/sonja/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/sonja/anaconda3/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

**Comment by adammcmaster** [comment]
Retry is not used for POST requests to the API (for the reason you suggested, i.e. there's no way to know if the request was actually processed on the server-side so it's not generally safe to retry it). It _is_ used for the PUT request that uploads media though (since if it actually succeeded the first time there's no harm in overwriting the file with the same content): https://github.com/zooniverse/panoptes-python-client/blob/7dc7318d79065216c8857a1d142f771b81d461b3/panoptes_client/subject.py#L167

Having said that, I guess when it comes to creating subjects we could probably use a retry since in the worst case all it would do is create an orphaned subject that would get cleaned up automatically later.

**Comment by camallen** [comment]
I'm following up about the 'resume' functionality with the person that has the upload issue. If that help solve the issue then i think we can use that mechanism. 

Thanks for clarifying @adammcmaster - i'm not sure adding retry on the subject upload is the right strategy right now but worth considering if needed.

I'm closing this for now but happy to reopen if folks think it is warranted.

**Comment by vrooje** [comment]
I've just had a problem that seems to be related when trying to generate a new workflow-classification export from the CLI. In the below snippet I'm in admin mode, but I wasn't able to get this to work even without the `-a` flag.

```
(conda-oct2py) bash-3.2$ panoptes -a workflow download-classifications --generate 18169 export.csv
No handlers could be found for logger "panoptes_client"
Generating new export...
Traceback (most recent call last):
  File "/usr/local/bin/panoptes", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/panoptes_cli/commands/workflow.py", line 169, in download_classifications
    wait_timeout=generate_timeout
  File "/usr/local/lib/python2.7/site-packages/panoptes_client/exportable.py", line 74, in get_export
    export = self.wait_export(export_type, wait_timeout)
  File "/usr/local/lib/python2.7/site-packages/panoptes_client/exportable.py", line 118, in wait_export
    export_type,
  File "/usr/local/lib/python2.7/site-packages/panoptes_client/exportable.py", line 178, in describe_export
    self._export_path(export_type),
  File "/usr/local/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 623, in http_get
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 320, in get
    retry=retry,
  File "/usr/local/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 267, in json_request
    retry=retry,
  File "/usr/local/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 236, in http_request
    json=json,
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(54, 'Connection reset by peer'))
```

Note I seem to also be missing something I need for logging as I get that `No handlers could be found` warning every time I use the CLI. 

Following this error, I can re-run the command without the `--generate` flag and download the export just fine. 


I initially also had issues today with uploading subjects, both on the PFE web interface and the CLI, but I think that was a combination of a bad internet connection followed by my not initially realising I was in an environment still using the pre-Azure CLI. Once I upgraded inside the environment, the upload worked fine. The above is using v1.1.3.

Not sure I am able to assign @camallen directly so tagging just in case. :)
