### ISSUE TITLE
Problem with subject_set upload_subjects: 'unicode' has no 'close'

### ISSUE THREAD

**Issue by justkristin** [zooniverse/panoptes-cli#41]
[Thu Jun 01 01:30 PM]  [knielsen@MooseAndSquirrel ../L8_May_To_Oct_2016]$ **panoptes subject_set upload_subjects 12528 manifest.csv**
Uploading subjects  [------------------------------------]    0%
Traceback (most recent call last):
  File "/usr/local/bin/panoptes", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/panoptes_cli/commands/subject_set.py", line 123, in upload_subjects
    subject.save()
  File "/usr/local/lib/python2.7/site-packages/panoptes_client/subject.py", line 63, in save
    image_file.close()
AttributeError: 'unicode' object has no attribute 'close'

My setup is:
OS X Sierra 10.12.5 (16F73)
Python 2.7.13 (default, Apr 22 2017, 15:55:54)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.41)] on darwin 

I wish I could Python, but all I can do is guess. Does
_image_file.close() - 'unicode' has no 'close'_
mean that image_file was expecting to handle a file of a certain type (unicode), but it is instead being given the string for the filename instead of the file itself? Sorry. I can break things, but I can't fix 'em.

**Comment by justkristin** [comment]
Tried again after realizing that I needed to do -m image/jpeg, but that didn't help either, with or without the "-r 1":

[Thu Jun 01 04:23 PM]  [knielsen@MooseAndSquirrel ../L8_May_To_Oct_2016]$ _panoptes subject_set upload_subjects -m image/jpeg 12528 manifest.csv_
Uploading subjects  [------------------------------------]    0%
Traceback (most recent call last):
  File "/usr/local/bin/panoptes", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/panoptes_cli/commands/subject_set.py", line 123, in upload_subjects
    subject.save()
  File "/usr/local/lib/python2.7/site-packages/panoptes_client/subject.py", line 63, in save
    image_file.close()
AttributeError: 'unicode' object has no attribute 'close'
[Thu Jun 01 04:25 PM]  [knielsen@MooseAndSquirrel ../L8_May_To_Oct_2016]$ **panoptes subject_set upload_subjects -m image/jpeg -r 1 12528 manifest.csv**
Uploading subjects  [------------------------------------]    0%
Traceback (most recent call last):
  File "/usr/local/bin/panoptes", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/panoptes_cli/commands/subject_set.py", line 123, in upload_subjects
    subject.save()
  File "/usr/local/lib/python2.7/site-packages/panoptes_client/subject.py", line 63, in save
    image_file.close()
AttributeError: 'unicode' object has no attribute 'close'

**Comment by astopy** [comment]
This is actually a bug that we've fixed recently (zooniverse/panoptes-python-client#98), but the fix hasn't been released yet. For now, if you run this to manually upgrade your copy of the client it should start working:

```
pip install -U git+git://github.com/zooniverse/panoptes-python-client.git
```

**Comment by justkristin** [comment]
Wow! That took care of it, sir! Thank you!
