### ISSUE TITLE
panoptes not working on command line

### ISSUE THREAD

**Issue by negna** [zooniverse/panoptes-cli#77]
While trying to remove subject sets from a workflow through command line, I was receiving errors that my workflow ID did not exist (although it definitely does), however, it worked when using python client without making any modifications to the settings of the workflow. Any thoughts to why command line may not be functioning properly?

**Comment by astopy** [comment]
Could you let me know the exact command you ran when you got the error?

**Comment by negna** [comment]
thanks so much for getting back to me.. i ran the following code 

Nicoles-MacBook:~ nicoleegna$ panoptes workflow remove-subject-sets 6831 15957 15924 15707 15712 15713 15721 15752 15925 15953 15963 15967

and the following was returned...

Traceback (most recent call last):
  File "/Users/nicoleegna/anaconda2/bin/panoptes", line 11, in <module>
    sys.exit(cli())
  File "/Users/nicoleegna/anaconda2/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/nicoleegna/anaconda2/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/nicoleegna/anaconda2/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/nicoleegna/anaconda2/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/nicoleegna/anaconda2/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/nicoleegna/anaconda2/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/nicoleegna/anaconda2/lib/python2.7/site-packages/panoptes_cli/commands/workflow.py", line 97, in remove_subject_sets
    workflow.remove_subject_sets(subject_set_ids)
  File "/Users/nicoleegna/anaconda2/lib/python2.7/site-packages/panoptes_client/utils.py", line 49, in do_batch
    func(_self, _batch, *args, **kwargs)
  File "/Users/nicoleegna/anaconda2/lib/python2.7/site-packages/panoptes_client/workflow.py", line 95, in remove_subject_sets
    '{}/links/subject_sets/{}'.format(self.id, _subject_set_ids)
  File "/Users/nicoleegna/anaconda2/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 524, in http_delete
    json
  File "/Users/nicoleegna/anaconda2/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 358, in delete
    endpoint=endpoint
  File "/Users/nicoleegna/anaconda2/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 221, in json_request
    json_response['errors']
panoptes_client.panoptes.PanoptesAPIException: Could not find workflow with id='6831'

however when i checked to see what workflow ids were present, 6831 is listed...

Nicoles-MacBook:~ nicoleegna$ panoptes workflow ls -p 2789
2030 What types of wildlife appear?
3914 test
5998 What types of wildlife appear 2.04.2018
6460 What types of wildlife appear 4.5.2018new workflow title
6831 workflow3

**Comment by astopy** [comment]
Could you make sure that you've run `panoptes configure` and entered the correct username and password? I can reproduce this here when I'm not logged in or I don't have access to modify the workflow.

I'm not sure if we'll be able to make the error message more helpful here or not, since I think the API will always return a not found error instead of forbidden in this case.

**Comment by negna** [comment]
Oh shoot, yes think that was the issue. Thanks so much!

**Comment by astopy** [comment]
Great, glad you've got it working now then.
