### ISSUE TITLE
can't upload data using latest head with async saves

### ISSUE THREAD

**Issue by camallen** [zooniverse/panoptes-cli#83]
can't upload subject on master using Dockerfile.dev on https://github.com/zooniverse/panoptes-cli/commit/5227dda22fea61c83bff3386e79f9d66f85b8d11

it's happening to both multi image and single image manifests, e.g one of the test manifests looks like the multi image one is much larger but has the same errors.
```
Subject_No,image1
611379-611380-611381,Ba-Bat01_03507_2-12-2016_11-29-55.JPG
```
Stack trace
```
 docker-compose run --rm dev -a subject-set upload-subjects 56577 /upload_data/WSCW_Zooniverse_manifest_2018.csv
Uploading subjects  [------------------------------------]    0%
Traceback (most recent call last):
  File "/usr/local/bin/panoptes", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/panoptes_cli/commands/subject_set.py", line 227, in upload_subjects
    move_created(MAX_PENDING_SUBJECTS)
  File "/usr/local/lib/python3.7/site-packages/panoptes_cli/commands/subject_set.py", line 201, in move_created
    if subject.async_save_result():
TypeError: 'bool' object is not callable
```

**Comment by adammcmaster** [comment]
@camallen Thanks!
