### ISSUE TITLE
Unable to upload video files

### ISSUE THREAD

**Issue by wgranger** [zooniverse/panoptes-cli#84]
I'm getting a similar error to #81 (`Locations is invalid`) however, I do have libmagic installed. Trying to upload a manifest with three subjects that are .mp4 extension and held locally. I've also tried setting the `-m` flag to `video/mp4` for kicks (with the required remote location flag), but to no avail.

**Comment by wgranger** [comment]
@adammcmaster 

**Note**: projects have been able to upload video subjects; however, they have been experiencing issues lately.

I've tried these commands:

`panoptes subject-set upload-subjects 6348 manifest.csv`
`panoptes subject-set upload-subjects -m video/mp4 -r 1 6348 manifest.csv`

`panoptes info`
<img width="343" alt="screen shot 2018-09-20 at 4 08 10 pm" src="https://user-images.githubusercontent.com/14099077/45847082-660af580-bcef-11e8-9c54-70a3674245bc.png">

**Comment by camallen** [comment]
The subject create logs show that the mime type is being set to `"image/None"` for these uploads. The issue is that the cli tool isn't detecting the mime type correctly from the filesystem and using this in the subject create request payload.

**Comment by wgranger** [comment]
Libmagic was the culprit here despite the output from `panoptes info`. `brew install libmagic` did the trick.

**Comment by celdermire** [comment]
I've tried downloading the most recent libmagic version (1.0) via pip on a windows 64 box that i'm using for my video transcoding; panoptes info still shows libmagic at 0.4.15. Is this an issue of dependencies with win64 boxes, or perhaps using python 3.6.6? I tried downloading libmagic dlls for w64 machines  (https://github.com/pidydx/libmagicwin64) but after placing the dlls in the specified place just got this sequence of error messages from the command line:

`C:\Upload1>panoptes subject-set upload-subjects 58179 manifest.csv
Uploading subjects  [------------------------------------]    0%
Traceback (most recent call last):
  File "c:\users\birdcam\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\birdcam\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\birdcam\AppData\Local\Programs\Python\Python36\Scripts\panoptes.exe\__main__.py", line 9, in <module>
  File "c:\users\birdcam\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\birdcam\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\birdcam\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\birdcam\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\birdcam\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\birdcam\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\birdcam\appdata\local\programs\python\python36\lib\site-packages\panoptes_cli\commands\subject_set.py", line 203, in upload_subjects
    subject.add_location(media_file)
  File "c:\users\birdcam\appdata\local\programs\python\python36\lib\site-packages\panoptes_client\subject.py", line 120, in add_location
    media_type = magic.from_buffer(media_data, mime=True)
  File "c:\users\birdcam\appdata\local\programs\python\python36\lib\site-packages\magic.py", line 147, in from_buffer
    m = _get_magic_type(mime)
  File "c:\users\birdcam\appdata\local\programs\python\python36\lib\site-packages\magic.py", line 123, in _get_magic_type
    i = _instances[mime] = Magic(mime=mime)
  File "c:\users\birdcam\appdata\local\programs\python\python36\lib\site-packages\magic.py", line 67, in __init__
    magic_load(self.cookie, magic_file)
  File "c:\users\birdcam\appdata\local\programs\python\python36\lib\site-packages\magic.py", line 264, in magic_load
    return _magic_load(cookie, coerce_filename(filename))
  File "c:\users\birdcam\appdata\local\programs\python\python36\lib\site-packages\magic.py", line 195, in errorcheck_negative_one
    raise MagicException(err)
magic.MagicException: None'

Suffice to say still unable to upload mp4 videos.

**Comment by camallen** [comment]
Do you have multiple versions of python installed on that system? It seems that was the issue that resolved this last time, i.e. the python running the panoptes uploader was different from the one reporting in `panoptes info` and didn't have access to the libmagic code. 

I'd uninstall the custom libmagic dll's you've added and `pip uninstall python-magic` as well. Look at starting from a blank slate if you can. https://github.com/ahupp/python-magic#windows

You can try and run this script to test your default python install independently https://github.com/zooniverse/panoptes-cli/issues/84#issuecomment-423455217

Also you can can use a docker image to run the cli tool, though docker and windows aren't that easy to get going. You should be able to run it from 
`docker-compose run stable --help` 
`docker-compose run stable subject-set upload-subjects 58179 manifest.csv` 
https://github.com/zooniverse/panoptes-cli/blob/master/CONTRIBUTING.md#getting-started

Though you might have to fiddle around with getting your `C:\Upload1>` directory mounted into the running container.

**Comment by camallen** [comment]
Excellent to hear you've got it working. Any feedback on a working windows setup would be appreciated.

**Comment by trouille** [comment]
@adammcmaster Are there any possible workarounds you can think of for windows machine users?

**Comment by celdermire** [comment]
@trouille I was unable to get it to work, and was under a time crunch to get the files uploaded, so didn't have the time to poke around once I knew it would work off my mac laptop. Sorry! I'm still interested in a windows solution, because I have a number of machines at my disposal but only my personal computer is a mac.

**Comment by srallen** [comment]
Windows users could use Docker for Windows and run a Unix environment using Docker. Then run the panoptes-cli in that Docker container.

**Comment by trouille** [comment]
Email from Colleen Stephens of Chimp&See about using Windows with panoptes-cli. Posting here in case others using Windows can benefit from the info:

I have figured out how to upload subjects with the CLI on a windows machine. I am able to run everything using ubuntu windows subsystem for linux. So far, everything is going well.

Last, I'm attaching 2 images that show a couple of error messages I got while figuring this out. These occurred because my security suite is overly paranoid, so I had to turn it off while uploading. So if anyone gets any of the errors in the images while in a similar situation to ours, that might be a possible reason.

![error message upload subjects1](https://user-images.githubusercontent.com/4975655/49399927-4b4df780-f708-11e8-9487-1f57be37aae1.png)

![error message upload subjects2](https://user-images.githubusercontent.com/4975655/49399933-4e48e800-f708-11e8-8294-700022d65cf7.png)

**Comment by celdermire** [comment]
Great point about ubuntu windows subsystem for linux—I may try to set this up next time around—should save me a couple hours...
