### ISSUE TITLE
fatal error: 'magic.h' file not found

### ISSUE THREAD

**Issue by sheishistoric** [zooniverse/panoptes-cli#95]
Have installed python-libmagic, libmagic, and python-magic, but on 
`panoptes info`
and
`panoptes configure`
thrown up with this error 
```
/anaconda3/lib/python3.7/site-packages/magic/__pycache__/_cffi__x7681a35x54cebdac.c:208:10: fatal error: 'magic.h' file not found
#include <magic.h>
```
and 
`repeated command 'gcc' failed with exist status 1`

**Comment by camallen** [comment]
Hey @sheishistoric - mind letting us if you found a solution for your problem? It may help other folks if they come across the same error.

**Comment by sheishistoric** [comment]
I found a solution to the error by uninstalling the three packages, but still having issues with the above commands.

**Comment by sheishistoric** [comment]
Different issue, this occurs regularly & in a virtual environment on a Mac. None of the modules mentioned above have been installed. Error occurs for both `panoptes configure` and `panoptes info`

```
(sample) bash-3.2$ panoptes configure
Broken libmagic installation detected. The python-magic module is installed but can't be imported. Please check that both python-magic and the libmagic shared library are installed correctly. Uploading media other than images may not work.
Traceback (most recent call last):
  File "/Users/estene/.local/share/virtualenvs/sample-KgF-lgoN/bin/panoptes", line 10, in <module>
    sys.exit(cli())
  File "/Users/estene/.local/share/virtualenvs/sample-KgF-lgoN/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/estene/.local/share/virtualenvs/sample-KgF-lgoN/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/estene/.local/share/virtualenvs/sample-KgF-lgoN/lib/python3.7/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/Users/estene/.local/share/virtualenvs/sample-KgF-lgoN/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/estene/.local/share/virtualenvs/sample-KgF-lgoN/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/estene/.local/share/virtualenvs/sample-KgF-lgoN/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/estene/.local/share/virtualenvs/sample-KgF-lgoN/lib/python3.7/site-packages/panoptes_cli/scripts/panoptes.py", line 47, in cli
    admin=admin,
  File "/Users/estene/.local/share/virtualenvs/sample-KgF-lgoN/lib/python3.7/site-packages/panoptes_client/panoptes.py", line 108, in connect
    cls._local.panoptes_client = cls(*args, **kwargs)
  File "/Users/estene/.local/share/virtualenvs/sample-KgF-lgoN/lib/python3.7/site-packages/panoptes_client/panoptes.py", line 140, in __init__
    self.login()
  File "/Users/estene/.local/share/virtualenvs/sample-KgF-lgoN/lib/python3.7/site-packages/panoptes_client/panoptes.py", line 484, in login
    'authenticity_token': self.get_csrf_token(),
  File "/Users/estene/.local/share/virtualenvs/sample-KgF-lgoN/lib/python3.7/site-packages/panoptes_client/panoptes.py", line 519, in get_csrf_token
    return self.session.get(url, headers=headers).headers['x-csrf-token']
  File "/Users/estene/.local/share/virtualenvs/sample-KgF-lgoN/lib/python3.7/site-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'x-csrf-token'
```

**Comment by sheishistoric** [comment]
Figured out the KeyError was due to the endpoint being redirected to a project user page instead of zooniverse login page. Still throwing up an error, as `panoptes info` and `panoptes configure` expect to already be logged in at this point. We manually went in and changed the code to include my username/password, but it shows an incorrect password error.

**Comment by camallen** [comment]
The password error may be due to the wrong API (staging vs production). Which end point are you using? What is the output of `panoptes info` (if you can get any)?

Do you have any code you can link to (scrub you user credentials before sharing) that we can have a look at? It'll help us debug what you are experiencing.

**Comment by sheishistoric** [comment]
here's the new error I'm getting for `panoptes info` - you can see that we noted the endpoint it was getting & rerouted it in the code. 

I'm heading out for the workday, but will be back tomorrow. We didn't change anything in the code except asking it to print the endpoint for us. We have no idea how it was getting this endpoint, as we never logged in previously.

```
looking at endpoint https://www.zooniverse.org/projects/judaicadh/scribes-of-the-cairo-geniza/
saving endpoint https://www.zooniverse.org/
log in status_code 200
URL log-in https://www.zooniverse.org//users/sign_in
failed response history []
Traceback (most recent call last):
  File "/anaconda3/bin/panoptes", line 10, in <module>
    sys.exit(cli())
  File "/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/anaconda3/lib/python3.6/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/panoptes_cli/scripts/panoptes.py", line 47, in cli
    admin=admin,
  File "/anaconda3/lib/python3.6/site-packages/panoptes_client/panoptes.py", line 108, in connect
    cls._local.panoptes_client = cls(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/panoptes_client/panoptes.py", line 142, in __init__
    self.login()
  File "/anaconda3/lib/python3.6/site-packages/panoptes_client/panoptes.py", line 505, in login
    response.json().get('error', 'Login failed')
panoptes_client.panoptes.PanoptesAPIException: Invalid email or password.
(base) wiccam1:~ estene$ 
```

**Comment by sheishistoric** [comment]
It may be important to note that while the URL login https://www.zooniverse.org//users/sign_in when entered in a browser will normally go to that page, the Chrome browser redirects it to https://panoptes.zooniverse.org/. Not sure if that's an issue as well?

**Comment by camallen** [comment]
Can you please just remove your cli tool configuration file and run the `panoptes configure` script again?
1. `rm -f ~/.panoptes/config.yml`
0. `panoptes configure` (put your user name and password and keep the default end point).

**Comment by sheishistoric** [comment]
`panoptes configure` works properly, `panoptes info` does not. And the rest of the commands worked fine - I was able to upload a subject set.

**Comment by camallen** [comment]
Ok great you can upload a subject set - just confirming that was after you removed the old configuration file?

what is the output of `panoptes info` now?

**Comment by sheishistoric** [comment]
Correct, that was after the removed old configuration file. 

This is the output of `panoptes info`: 
```
Traceback (most recent call last):
  File "/anaconda3/bin/panoptes", line 10, in <module>
    sys.exit(cli())
  File "/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/panoptes_cli/commands/info.py", line 16, in info
    pkg_resources.require("panoptescli")[0].version
  File "/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (PyYAML 3.13 (/anaconda3/lib/python3.6/site-packages), Requirement.parse('PyYAML<3.13,>=3.12'), {'panoptescli'})
```

**Comment by adammcmaster** [comment]
It looks like the version of PyYAML installed is newer than the newest version supported by the CLI. I'm going to try to release an update to fix that this week.

**Comment by sheishistoric** [comment]
Thanks!

**Comment by adammcmaster** [comment]
Just to let you know, I just released an update that allows the newer version.
