### ISSUE TITLE
Add validation for endpoint config option

### ISSUE THREAD

**Issue by denslowm** [zooniverse/panoptes-cli#96]
Today when I went to use panoptes-cli I got an error message for any commands I try.

I do a fresh install each time and tried both:
`pip install panoptescli`
and 
`pip install -U git+git://github.com/zooniverse/panoptes-python-client.git` EDIT by MB: added `@v1.0.3` to many attempts

When I try my usual command to upload subjects, I get the following. I also tried panoptes configure and panoptes info which also give me errors.

No handlers could be found for logger "panoptes_client"
Traceback (most recent call last):
  File "/Users/michaeldenslow/panoptes/venv/bin/panoptes", line 11, in <module>
    sys.exit(cli())
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/panoptes_cli/scripts/panoptes.py", line 47, in cli
    admin=admin,
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 108, in connect
    cls._local.panoptes_client = cls(*args, **kwargs)
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 140, in __init__
    self.login()
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 484, in login
    'authenticity_token': self.get_csrf_token(),
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 519, in get_csrf_token
    return self.session.get(url, headers=headers).headers['x-csrf-token']
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/requests/models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/requests/models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'y/users/sign_in': No schema supplied. Perhaps you meant http://y/users/sign_in?

**Comment by denslowm** [comment]
I spent some time trying to troubleshoot this with Mark and it's still not resolved. Here is some more information that might be helpful. 

I am running osX High Sierra 10.13.6

`python --version && pip --version` gives me:

(venv) BIO-02NK3RUG3QJ:panoptes michaeldenslow$ python --version && pip --version
Python 2.7.10
pip 19.0.2 from /Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/pip (python 2.7)

To reiterate I use the panoptes-cli frequently and had no issues at all last week. I can't think of anything that has changed on my end since that time.

**Comment by mcbouslog** [comment]
Downgraded to use a v1.0 of `panoptes-python-client` and appears to be working as usual.

**Comment by mcbouslog** [comment]
With `panoptes info` of:
```
PyYAML: 3.12
Operating system: Darwin 17.7.0
Python version: 2.7.10
Panoptes client version: 1.0.3 **AND ALSO TRIED** 1.1.0
libmagic: 0.4.13
API endpoint: https://www.zooniverse.org
Panoptes CLI version: 1.0.1
Click: 6.7
```
now getting "Received HTTP status code 504 from API."

**Comment by camallen** [comment]
This could be related to some changes in how the client is issuing API requests to the zooniverse API, i.e. lots of fast running requests and normal load is causing the servers to get too busy to fulfill the volume of requests in a timely manner (60s at the load balancer). 

I'd say that's probably not what's happening though and more likely the servers just got busy at the time they tried to upload data. @mcbouslog can you please follow up with the research team and report back what they found.

**Comment by denslowm** [comment]
A quick update, after much trial and error and hand holding from @mcbouslog  I was able to load the 4 subject sets. However, it took several tries so I am unclear exactly what went wrong and how to fix it. 

I'd like to leave this open until I know for certain how to install and use the current version.

**Comment by mcbouslog** [comment]
@denslowm and I are going to revisit the issues experienced and will update this issue accordingly, but until then some quick notes:
- I'm not sure about the original error experienced, that included: `File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/requests/models.py", line 379, in prepare_url
raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'y/users/sign_in': No schema supplied. Perhaps you meant http://y/users/sign_in?`. It may have had something to do with how the `panotpes-client` was installed on @denslowm's machine. To utilize the improved upload behavior, prior to the `panoptes-client` 1.1.0 release, it was [installed directly from GitHub](https://github.com/zooniverse/panoptes-python-client#installation). Maybe once the 1.1.0 release went live, that install caused issues?
- the 504 issues appear to have been resolved
- I think we also experienced https://github.com/zooniverse/panoptes-python-client/issues/205

**Comment by adammcmaster** [comment]
* The `invalid URL` error comes from having an invalid value for the endpoint in the configuration. In this case it seems to have been set to `y` rather than www.zooniverse.org.
* The 504s will be a thing of the past once version 1.1 is out (because it will use the new Python client which retries on errors).

**Comment by adammcmaster** [comment]
I think the main takeaway from this issue is that the CLI should validate the endpoint. It probably shouldn't prompt the user to change it during a normal `panoptes configure` either, since almost everyone will want to use the default value.

**Comment by denslowm** [comment]
A follow up question on this issue as I am trying to use the tool today. 

I installed via `pip install panoptescli` today. 

My `panoptes info` says:
PyYAML: 3.12
Operating system: Darwin 17.7.0
Python version: 2.7.10
Panoptes client version: 1.0.3
libmagic: 0.4.13
API endpoint: https://www.zooniverse.org
Panoptes CLI version: 1.0.1
Click: 6.7

Is this correct? I thought the CLI version was supposed to 1.0.2

**Comment by mcbouslog** [comment]
Also try `pip install -U panoptes-client` then try `panoptes info` again and hopefully it will show the "Panoptes client version: 1.1.1".

For the Panoptes-CLI v1.0.2 is the correct or must up to date version.

**Comment by mcbouslog** [comment]
I'm sorry, and also run `pip install -U panoptescli` to hopefully update the Panoptes-CLI from v1.0.1 to v1.0.2.

**Comment by denslowm** [comment]
Thanks. I ran `pip install -U panoptescli` then `panoptes info`
Now I get this:
PyYAML: 3.12
Operating system: Darwin 17.7.0
Python version: 2.7.10
Panoptes client version: 1.0.3
libmagic: 0.4.13
API endpoint: https://www.zooniverse.org
Panoptes CLI version: 1.0.2
Click: 6.7

**Comment by mcbouslog** [comment]
That's good the Panoptes CLI is now v1.0.2. 

Could you also run `pip install -U panoptes-client` and check if you've bumped the "Panoptes client version" up to 1.1.1 from 1.0.3?

**Comment by denslowm** [comment]
I ran `pip install -U panoptes-client` and `panoptes info` now says:

No handlers could be found for logger "panoptes_client"
PyYAML: 3.12
Operating system: Darwin 17.7.0
Python version: 2.7.10
Panoptes client version: 1.1.1
libmagic: 0.4.13
API endpoint: https://www.zooniverse.org
Panoptes CLI version: 1.0.2
Click: 6.7

**Comment by mcbouslog** [comment]
Looking good! I think it should work well now, including upload resumes on common issues and the other latest features.

**Comment by denslowm** [comment]
OK, so for my install I should just replace `pip install panoptescli` with `pip install -U panoptes-client` from now on?

**Comment by mcbouslog** [comment]
I think you're primarily using the panoptes-CLI, which depends on the panoptes-client. You can check the latest released versions:
- [panoptes-CLI](https://github.com/zooniverse/panoptes-cli/releases)
- [panoptes-client](https://github.com/zooniverse/panoptes-python-client/releases)

Then you can check what you have locally with 'panoptes info'. If need to upgrade one you'll only need to run whichever is behind with either:
- `pip install -U panoptescli` will update the panoptes-CLI
- `pip install -U panoptes-client` will update the panoptes-client

Always good to check the updates first though to see if it'll change how you're using the panoptes-CLI.

**Comment by denslowm** [comment]
Sounds good. I think we can probably close this for now. I'll reopen if I encounter additional issues.

**Comment by denslowm** [comment]
Unfortunately, I need to reopen this. See below:

(venv) BIO-02NK3RUG3QJ:subjectsPython michaeldenslow$ `panoptes info`

No handlers could be found for logger "panoptes_client"
PyYAML: 3.12
Operating system: Darwin 17.7.0
Python version: 2.7.10
Panoptes client version: 1.1.1
libmagic: 0.4.13
API endpoint: https://www.zooniverse.org
Panoptes CLI version: 1.0.2
Click: 6.7

After trying the following command:
(venv) BIO-02NK3RUG3QJ:subjectsPython michaeldenslow$ `panoptes subject-set upload-subjects 73711 33a72b22-f702-4088-9833-ebbad90b7c17-ascii.csv`

I get:
No handlers could be found for logger "panoptes_client"
Uploading subjects  [##----------------------------------]    6%  1d 01:34:06
Traceback (most recent call last):
  File "/Users/michaeldenslow/panoptes/venv/bin/panoptes", line 10, in <module>
    sys.exit(cli())
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/panoptes_cli/commands/subject_set.py", line 223, in upload_subjects
    subject_set.add(created_subjects)
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/panoptes_client/subject_set.py", line 95, in add
    return self.links.subjects.add(subjects)
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/panoptes_client/subject_set.py", line 40, in add
    return super(SubjectSetLinkCollection, self).add(objs)
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/panoptes_client/utils.py", line 56, in do_batch
    func(_self, batch, *args, **kwargs)
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 1037, in add
    _objs = [obj for obj in self._build_obj_list(objs) if obj not in self]
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/panoptes_client/subject_set.py", line 27, in __contains__
    subject_id=_subject_id
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 672, in where
    return cls.paginated_results(*cls.http_get(_id, params=kwargs))
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 623, in http_get
    **kwargs
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 320, in get
    retry=retry,
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 267, in json_request
    retry=retry,
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 243, in http_request
    response.status_code
panoptes_client.panoptes.PanoptesAPIException: Received HTTP status code 504 from API

**Comment by eatyourgreens** [comment]
>panoptes_client.panoptes.PanoptesAPIException: Received HTTP status code 504 from API

504 is a timeout error. Is this problem ongoing? It could be that you were trying to upload files at a time when our API servers were being slow for some reason. I'm not sure this is a problem in the client, unless it's supposed to handle timeouts by retrying the request.

**Comment by denslowm** [comment]
Yes, this has been a problem in the past. I thought that the new version retried the upload.

I tried the entire upload again overnight and it failed with the same error, but at a different point.

**Comment by srallen** [comment]
How many subjects are you trying to upload in a batch?

**Comment by denslowm** [comment]
This particular set is big (~15,000), but I have experienced this issue with much smaller subjects sets.

**Comment by adammcmaster** [comment]
My hunch is that the API request timed out every time it retried (it tries five times, with a delay between attempts). We've been having some recent issues with the API responding slowly which could be causing this. The retries will handle requests that fail because of really brief server issues, but if it's slow for a few minutes at a time that'll still cause the upload to fail. 

I'm not sure what the best option is here. Should we maybe make the retries more aggressive?

**Comment by denslowm** [comment]
I'm really not sure. What does the Project Builder do in this case? 

Maybe there could be a way to resume the process? Each time this happens, I delete the partial subject set and start completely over.

**Comment by adammcmaster** [comment]
I'm not sure if the project builder handles those errors at all, so the uploads there will probably just wait without retrying.

We've had some thoughts about making uploads resumable. It's something we'd like to do eventually, but I'm not sure when that's likely to be implemented.

**Comment by srallen** [comment]
The old panoptes-subject-uploader has an offset parameter so that you can tell it which row in the csv manifest to start with. If on error, we can log for the user which row it errored on and the cli has a parameter like this, they can at least tell it to start again where it left off manually.

**Comment by denslowm** [comment]
Thanks. It sounds like I will be meeting with Laura about this some time next week to discuss solutions.
